#include "RuntimeState.hpp"

namespace google_ui {

RuntimeState gState = {
    .vm = nullptr,
    .moduleEnabled = true,
    .hooksInstalled = false,
    .uiVisible = false,
    .websiteUiVisible = false,
    .layoutInitialized = false,
    .settingsLoaded = false,
    .buttonPaddingFixed = false,
    .rootWidth = 0,
    .rootHeight = 0,
    .density = 1.0F,
    .x = 0,
    .y = 0,
    .width = 0,
    .height = 0,
    .titleHeight = 0,
    .margin = 0,
    .buttonX = 24,
    .buttonY = 240,
    .buttonSize = 0,
    .buttonOpacityPercent = 100,
    .buttonCommandSequence = 0,
    .adBlockPollCounter = 0,
    .websiteAdBlockPollCounter = 0,
    .syntheticDrawRevision = 0,
    .modRootPath = {},
    .websiteUrl = "https://www.google.com",
    .activity = nullptr,
    .root = nullptr,
    .container = nullptr,
    .titleBarWebView = nullptr,
    .webView = nullptr,
    .buttonActivity = nullptr,
    .buttonRoot = nullptr,
    .buttonWebView = nullptr,
    .websiteActivity = nullptr,
    .websiteRoot = nullptr,
    .websiteContainer = nullptr,
    .websiteTitleBarWebView = nullptr,
    .websiteWebView = nullptr,
    .adBlockClassLoader = nullptr,
    .adBlockClientClass = nullptr,
    .adBlockClient = nullptr,
    .websiteAdBlockClassLoader = nullptr,
    .websiteAdBlockClientClass = nullptr,
    .websiteAdBlockClient = nullptr,
    .preloaderHandle = nullptr,
    .infosHook = nullptr,
    .toggleHook = nullptr,
    .configHook = nullptr,
    .revisionHook = nullptr,
    .drawHook = nullptr,
    .buttonCountHook = nullptr,
    .buttonInfoHook = nullptr,
    .buttonIconHook = nullptr,
    .buttonEventHook = nullptr,
    .originalInfos = nullptr,
    .originalToggle = nullptr,
    .originalConfig = nullptr,
    .originalRevision = nullptr,
    .originalDraw = nullptr,
    .originalButtonCount = nullptr,
    .originalButtonInfo = nullptr,
    .originalButtonIcon = nullptr,
    .originalButtonEvent = nullptr,
};

char gModuleInfoJson[kModuleInfoJsonCapacity];
char gBulkModuleInfoJson[kBulkModuleInfoJsonCapacity];

} // namespace google_ui
